[package]
name = "aidl-cli"
version = "0.1.0"
edition = "2021"

[dependencies]
aidl-parser = { path = "../aidl-parser" }
anyhow = "1.0"
codespan-reporting = "0.11"
structopt = "0.3"
tracing = "0.1"
tracing-subscriber = "0.3"
walkdir = "2.3"
