name: main

on: [push, pull_request]

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        include:
          - os: ubuntu-latest
            target: x86_64-unknown-linux-gnu
          - os: macos-latest
            target: x86_64-apple-darwin
          - os: windows-latest
            target: x86_64-pc-windows-gnu
    defaults:
      run:
        shell: bash
    steps:
      - uses: actions/checkout@v2

      - name: Install Rust toolchain
        uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: stable

      - name: Set up Rust cache
        uses: Swatinem/rust-cache@v1

      - name: Cargo build
        uses: actions-rs/cargo@v1
        with:
          command: build
          args: --release

      - name: Cargo clippy
        uses: actions-rs/cargo@v1
        with:
          command: clippy
          args: --release --all -- -D clippy::all

      - name: Cargo test
        uses: actions-rs/cargo@v1
        with:
          command: test

      - name: Create artifact folder
        run: |
            mkdir dist
            cp target/release/aidl-cli dist

      - name: Upload artifact
        uses: actions/upload-artifact@v2
        with:
            name: aidl-cli-${{ matrix.target }}
            path: |
                ./dist

